typedef signed char		int_8t;
typedef unsigned char		uint_8t;
typedef short			int_16t;
typedef unsigned short		uint_16t;
typedef int			int_32t;
typedef unsigned	int	uint_32t;
typedef long long		int_64t;
typedef unsigned long long	uint_64t;
typedef float float_32t;
typedef double float_64t;

typedef unsigned int boolean;
typedef volatile signed char		vint_8t;
typedef volatile unsigned char		vuint_8t;
typedef volatile short			vint_16t;
typedef volatile unsigned short		vuint_16t;
typedef volatile int			vint_32t;
typedef volatile unsigned	int	vuint_32t;
typedef volatile long long		vint_64t;
typedef volatile unsigned long long	vuint_64t;
typedef volatile float vfloat_32t;
typedef volatile double vfloat_64t;
